### ISSUE TITLE
DKP mess up

### ISSUE THREAD

**Issue by YoitsMeda** [Roeshambo/MonolithDKP#213]
So we had an issue where two officer migrated and messed up the tables. We have spent a few hours trying to just delete all of out data and starting over but we can't is there anything we can do to fix this issue to get everyone on the same table again?

**Comment by Roeshambo** [comment]
Did one of the officers happen to back up their Saved Variables file as suggested in the migration? If so, can you please post it here along with the migrating officers character name?

**Comment by YoitsMeda** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3954244/MonolithDKP.zip)
Officers:
Bloodstruck did the migration then Noxx synced it and messed it up.

**Comment by Roeshambo** [comment]
That table appears to be empty :/. They didn't back a copy up prior to migrating? Or perhaps is there someone else in the guild that has accurate data, even if it was after migration?

**Comment by YoitsMeda** [comment]
ok I got another one

**Comment by YoitsMeda** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3954300/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
That one looks like it'll work. Give me a moment

**Comment by Roeshambo** [comment]
Bloodstruck is the officer it should be indexed as?

**Comment by YoitsMeda** [comment]
No can you indexed Noxx or does it have to be Bloodstuck?

**Comment by Roeshambo** [comment]
It can be any officer. Just has to be an officer.

**Comment by Roeshambo** [comment]
*Officer with permission to manage the DKP within the addon anyway.

**Comment by YoitsMeda** [comment]
Ok then Noxx.
Bloodstuck did the migration does that effect anything?

**Comment by Roeshambo** [comment]
Nope. I'm reversing the migration and remigrating it all under one index

**Comment by YoitsMeda** [comment]
Dude you are awesome also do you take help on this app?

**Comment by Roeshambo** [comment]
Define help. Like testing?

**Comment by YoitsMeda** [comment]
testing help with code on anything just general help

**Comment by Roeshambo** [comment]
I'm never opposed to contributors if they want to throw something together to put in.

**Comment by Roeshambo** [comment]
I'm quite backed up on requests at the moment though. Especially with trying to get the whole broadcast system to a relatively flawless state.

**Comment by Roeshambo** [comment]
This look accurate to you?
![image](https://user-images.githubusercontent.com/6285297/70690948-7d7c2880-1c7d-11ea-929c-cc3d81caab07.png)

**Comment by YoitsMeda** [comment]
That is correct but we do need to adjust the dkp how do we do it without messing everything up again? Do I just have Noxx adjust everything then broadcast it?

**Comment by Roeshambo** [comment]
When I give it back, it doesn't matter who adjusts it as long as they have permissions (on the whitelist if you use one). But you're going to have to do some steps to get it integrated. It's been reindexed. Which means there will be people with incorrect indexing in the guild. I'll give you this file and just hang on to it until you have all officers online together. All of them will close their client and replace their saved variables file with this one so they all have identical indexing and don't risk broadcasting old indexes. Then you're going to have everyone in the guild wipe their tables (Button to do so in the Options tab) and relog. Then you can start syncing them. You'll most likely see "Missing Indexes" and an out of date tag on the status indicator. That's simply because others in the guild are reporting those old indexes as being missing. You can ignore that. It'll sort itself out when everyone gets their tables wiped and gets correct data eventually.

**Comment by Roeshambo** [comment]
Most important part is no officers get online with the any old data when an officer is online that has this new data.

**Comment by Roeshambo** [comment]
Once you've gotten past that speed bump, it's fine to use as normal.

**Comment by Roeshambo** [comment]
[MonolithDKP.zip](https://github.com/Roeshambo/MonolithDKP/files/3954392/MonolithDKP.zip)

**Comment by Roeshambo** [comment]
I'll have a new version out by this weekend that will be a bit more picky about what indexes it allows so as to avoid any issues like that all together.

**Comment by Stevenwu97** [comment]
Hey Roe, Im the Guildmaster over here (Noxx). I demoted every officer besides Meda(Smackdacks) so could we just do it with us two?
Also, its a social and raiding guild. So we need everyone with the monolith addon to wipe their tables?

**Comment by Roeshambo** [comment]
Yes that will work. As long as those officers that were online when you demoted them relog (the addon identifies someone as an officer on login. So if they were demoted after they already logged in and were identified as officers, they'll retain that officer status within the addon until they relog). As far as wiping, yes anyone that has bad data will need to wipe. All entries in that table are indexed as Noxx-1, Noxx-2 etc. If someone has an entry indexed as Bloodstruck-1, for example, Your status indicator on the bottom left will turn red and tell you that you're missing 1 entry from Bloodstruck.

**Comment by Roeshambo** [comment]
Having that notification that you're missing that one entry won't effect your DKP in the least. It'll just constantly tell you you're missing that entry.

**Comment by Stevenwu97** [comment]
Thank you for the help, hopefully we get this all sorted out. It would be nice to have like an override feature or something of that sorts.

**Comment by Roeshambo** [comment]
I'm working on getting some options in there to help control how data flows as well as a way to repair a table that may have gotten screwed somehow.

**Comment by Stevenwu97** [comment]
It wasn't pretty, but we sorted it out. It seems like the problem was just the two officers entries chaining on each other

**Comment by Stevenwu97** [comment]
The people here at <Exalted> really appreciate your help and dedication to the project, keep doing the lords work sir.

**Comment by Roeshambo** [comment]
No problem. It'll get better. Promise.

**Comment by Roeshambo** [comment]
If you have any more issues just comment and I'll address it.

**Comment by YoitsMeda** [comment]
I have a question is there anything special we have to do for the other officers in the guild to be able to have the Adjust DKP and Manage Tabs?

**Comment by Roeshambo** [comment]
"Edit Officer Notes" is the permission that gives that, unless there's a whitelist. Which I believe you were using.

**Comment by Stevenwu97** [comment]
I removed the whitelist last night but it seems to not recognize our officers. I demoted everyone and made them raiders until each officer had tables up to date, then i promoted them. 
[MonolithDKP.lua copy alias 2.zip](https://github.com/Roeshambo/MonolithDKP/files/3957519/MonolithDKP.lua.copy.alias.2.zip)

**Comment by Roeshambo** [comment]
Is there still an issue? That file appears to be in a format I can't read.

**Comment by Stevenwu97** [comment]
[MonolithDKP.lua.zip](https://github.com/Roeshambo/MonolithDKP/files/3957586/MonolithDKP.lua.zip)

**Comment by Stevenwu97** [comment]
Sorry i renamed it, it should be ok now. And yes, it still isn't letting our officers see the manage tab.

**Comment by Stevenwu97** [comment]
I removed the whitelist last night, but its not recognizing our officers and they can't even see the manage tab. All officers have permission to edit note as well. So im not sure what is going on. I did demote everyone last night while i fixed the tables, and i promoted them back to officer once their tables were solid.

**Comment by Roeshambo** [comment]
While they are online, go into your whitelist, with no one selected click the "Set Whitelist" (just to make sure it's empty). And then broadcast that whitelist to them. They very likely still have the whitelist even if you don't. The whitelist is a very iffy thing because it only works if everyone has the whitelist locally stored. If you change it when they aren't online they wouldn't see those changes reflected locally.

**Comment by Stevenwu97** [comment]
Sweet its working now! I guess i just have to broadcast the whitelist to everyone

**Comment by Roeshambo** [comment]
There is a script that broadcasts the whitelist if you're an officer and open the DKP menu. This is in place to try to ensure the list is propagated to everyone in the guild (so you don't have to monitor who may or may not have it and rebroadcast manually every time you change it). This, however, can work in reverse. You could clear your whitelist and then another officer could login with the old list, open their menu, and set your list back to where it was. So I would recommend you make sure to clear it and broadcast it when all officers are online. Now that I'm thinking about it, I should include a stipulation in there that an officer can't change the GMs list in that way. Been so busy with other stuff that the whitelist was kind of on the back burner. Hence why it's still in an alpha state.
